name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --logger:trx
    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Test Results
        # A file, directory or wildcard pattern that describes what to upload
        path: '**/*.trx'
    - name: Pack the NuGets
      run: dotnet pack --configuration Release --no-build
